branch-defaults:
  main:
    environment: jaswanth-progress-environment
    group_suffix: null
environment-defaults:
  jaswanth-progress-environment:
    branch: null
    repository: null
global:
  application_name: file-uploader-cloud
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
